name: jobmap
description: Jobmap Server
version: 0.0.1
author: Gurkan Yilmaz

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  mongo_dart: ^0.3.5
  html:
  http:
  cron:
  dio:


dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
  build_runner:
  build_web_compilers:
